-- MySQL Script generated by MySQL Workbench
-- Mon Jun 23 13:33:05 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`table1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`table1` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Authors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Authors` (
  `Authorid` INT NULL,
  `AuthorID` INT NOT NULL,
  `Name` VARCHAR(100) NULL,
  `Country` VARCHAR(50) NULL,
  PRIMARY KEY (`AuthorID`),
  INDEX `AuthorID_idx` (`Authorid` ASC) VISIBLE,
  CONSTRAINT `AuthorID`
    FOREIGN KEY (`Authorid`)
    REFERENCES `mydb`.`Authors` (`AuthorID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Books`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Books` (
  `BookID` INT NULL,
  `Title` VARCHAR(200) NULL,
  `Genre` VARCHAR(50) NULL,
  `ISBN` VARCHAR(20) NULL,
  `AuthorID` INT NULL,
  PRIMARY KEY (`BookID`),
  INDEX `AuthorID_idx` (`AuthorID` ASC) VISIBLE,
  CONSTRAINT `AuthorID`
    FOREIGN KEY (`AuthorID`)
    REFERENCES `mydb`.`Authors` (`AuthorID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Members`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Members` (
  `MemberID` INT NULL,
  `Name` VARCHAR(100) NULL,
  `JoinDate` DATE NULL,
  PRIMARY KEY (`MemberID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`BorrowRecords`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`BorrowRecords` (
  `RecordID` INT NULL,
  `MemberID` INT NULL,
  `BookID` INT NULL,
  `BorrowDate` DATE NULL,
  `ReturnDate` DATE NULL,
  PRIMARY KEY (`RecordID`),
  INDEX `MemberID_idx` (`MemberID` ASC) VISIBLE,
  INDEX `BookID_idx` (`BookID` ASC) VISIBLE,
  CONSTRAINT `MemberID`
    FOREIGN KEY (`MemberID`)
    REFERENCES `mydb`.`Members` (`MemberID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `BookID`
    FOREIGN KEY (`BookID`)
    REFERENCES `mydb`.`Books` (`BookID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`books`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`books` (
  `AuthorID` INT NOT NULL,
  `Name` VARCHAR(100) NULL,
  `Country` VARCHAR(50) NULL,
  PRIMARY KEY (`AuthorID`),
  CONSTRAINT `authors`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Books` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.``
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`` (
)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
